services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskxpro-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      #- vendor:/var/www/vendor
      #- node_modules:/var/www/node_modules
      #- public_build:/var/www/public/build
      - storage:/var/www/storage
      - bootstrap_cache:/var/www/bootstrap/cache
      - ./php/upload.ini:/usr/local/etc/php/conf.d/upload.ini:ro
    networks:
      - taskxpro-network

  web:
    image: nginx:alpine
    container_name: taskxpro-web
    restart: unless-stopped
    tty: true
    ports:
      - "8020:80"
    volumes:
      - ./:/var/www
      #- public_build:/var/www/public/build:ro
      - storage:/var/www/storage:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - taskxpro-network
    depends_on:
      - app

networks:
  taskxpro-network:
    driver: bridge

volumes:
  # vendor:
  # node_modules:
  # public_build:
  storage:
  bootstrap_cache:
