<?php

namespace Tests\Feature;

use App\Enums\TaskStatus;
use App\Models\KpiScore;
use App\Models\PhaseTemplate;
use App\Models\Project;
use App\Models\Task;
use App\Models\User;
use Database\Seeders\TaskXProSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class SeederIntegrityTest extends TestCase
{
    use RefreshDatabase;

    public function test_seeder_creates_essential_data(): void
    {
        $this->seed(TaskXProSeeder::class);

        // 1. Verify Users
        $this->assertDatabaseHas('users', ['email' => 'ceo@taskxpro.vn']);
        $this->assertDatabaseHas('users', ['email' => 'leader@taskxpro.vn']);
        $this->assertDatabaseHas('users', ['email' => 'pic@taskxpro.vn']);

        $ceo = User::where('email', 'ceo@taskxpro.vn')->first();
        $this->assertTrue($ceo->hasRole('ceo'));

        // 2. Verify Phase Templates
        $projectTypes = ['warehouse', 'customs', 'trucking', 'software', 'gms', 'tower'];
        foreach ($projectTypes as $type) {
            $this->assertTrue(
                PhaseTemplate::where('project_type', $type)->exists(),
                "Phase templates for {$type} missing"
            );
        }

        // 3. Verify Projects
        $this->assertGreaterThan(0, Project::count());
        $this->assertDatabaseHas('projects', ['type' => 'software']);
        $this->assertDatabaseHas('projects', ['type' => 'warehouse']);

        // 4. Verify Tasks and Dependencies
        $this->assertGreaterThan(0, Task::count());

        // Check dependency logic: If a task has a dependency, ensure the dependency exists
        $tasksWithDependency = Task::whereNotNull('dependency_task_id')->get();
        foreach ($tasksWithDependency as $task) {
            $this->assertNotNull($task->dependencyTask);
        }

        // 5. Verify KPI Scores
        $this->assertGreaterThan(0, KpiScore::count());

        // Check if a PIC with completed tasks has a KPI score
        // Use Enum for status check
        $completedTask = Task::where('status', TaskStatus::Completed)
            ->whereNotNull('pic_id')
            ->first();

        if ($completedTask) {
            $pic = $completedTask->pic;
            if ($pic) {
                $this->assertTrue(
                    KpiScore::where('user_id', $pic->id)->exists(),
                    "KPI Score for user {$pic->id} missing"
                );
            }
        } else {
            $this->markTestSkipped('No completed tasks generated by seeder to test KPI.');
        }
    }

    public function test_seeder_respects_business_logic(): void
    {
        $this->seed(TaskXProSeeder::class);

        // BR-008: Check Phase weights sum to roughly 100 (allow small float error or incomplete templates)
        // Note: Seeder sets default weights.
        $project = Project::first();
        if ($project) {
            $totalWeight = $project->phases()->sum('weight');
            // In our seeder logic, we copy template weights.
            // Templates sum to ~100. Let's assert it's close.
            $this->assertEqualsWithDelta(100, $totalWeight, 5, 'Project phase weights should sum to 100');
        }

        // BR-002: KPI Score Calculation
        // Pick a score and verify calculation
        $score = KpiScore::where('total_tasks', '>', 0)->first();
        if ($score) {
            $expected = ($score->on_time_rate * 0.4) + ($score->sla_rate * 0.4) + (($score->avg_star / 5 * 100) * 0.2);
            $this->assertEqualsWithDelta($expected, $score->final_score, 0.1, 'KPI calculation mismatch');
        }
    }
}
